project_name       = "terrformtest"
work_item_template = "Agile"
project_type       = "Mvc"
project_version    = "3.1"
hostname           = "crm"
apppoolusername    = "BCHTGROUP\\SVC-CRMUser"
apppoolpassword    = "password"